#!/usr/bin/env python3
"""
Interactive step-by-step guide for Azure AD app registration.

This script does NOT make API calls — it prints the exact steps to perform
in the Azure portal and records the values you paste into .env.

Usage:
    python scripts/setup_azure_ad.py
"""

import textwrap


def step(n: int, title: str, body: str) -> None:
    print(f"\n{'='*60}")
    print(f"  Step {n}: {title}")
    print(f"{'='*60}")
    print(textwrap.dedent(body).strip())


def prompt(label: str) -> str:
    value = input(f"\n  Enter {label}: ").strip()
    return value


def main() -> None:
    print("\n=== Azure AD + Bot Registration Setup ===")
    print("This wizard walks you through the one-time Azure setup.\n")

    step(1, "Register an Entra ID (Azure AD) app", """
    1. Go to https://portal.azure.com → Azure Active Directory → App registrations → New registration
    2. Name: OnboardingAgent
    3. Supported account type: Single tenant (your org only)
    4. Redirect URI: leave blank
    5. Click Register
    """)
    tenant_id = prompt("Tenant ID (Directory ID)")
    client_id = prompt("Application (Client) ID")

    step(2, "Create a client secret", """
    1. In your new app registration → Certificates & secrets → New client secret
    2. Description: onboarding-agent, Expires: 24 months
    3. Copy the VALUE immediately (it won't be shown again)
    """)
    client_secret = prompt("Client Secret VALUE")

    step(3, "Grant API permissions", """
    1. API permissions → Add a permission → Microsoft Graph → Application permissions
    2. Add: Files.ReadWrite.All, ChannelMessage.Send, Chat.Create, User.Read.All
    3. Click 'Grant admin consent for [your tenant]'
    """)

    step(4, "Get Excel file IDs", """
    1. Open the Excel file in SharePoint/OneDrive in a browser
    2. Check the URL for the drive ID and item ID, or use Graph Explorer:
       GET https://graph.microsoft.com/v1.0/me/drive/root/children
    """)
    drive_id = prompt("GRAPH_EXCEL_DRIVE_ID")
    item_id = prompt("GRAPH_EXCEL_ITEM_ID")
    sheet_name = prompt("GRAPH_EXCEL_SHEET_NAME (default: Onboarding)") or "Onboarding"

    step(5, "Get Teams IDs", """
    1. In Teams, right-click the channel → Get link to channel
    2. Extract team ID and channel ID from the URL
    """)
    team_id = prompt("TEAMS_TEAM_ID")
    channel_id = prompt("TEAMS_CHANNEL_ID")

    step(6, "Register an Azure Bot", """
    1. Portal → Create a resource → Azure Bot
    2. Bot handle: OnboardingAgentBot
    3. App type: Single tenant
    4. Use existing app registration → paste Client ID from step 1
    5. After creation → Channels → Microsoft Teams → Save
    6. Configuration → Messaging endpoint: https://YOUR_HOST/api/messages
    """)
    bot_app_id = prompt("MICROSOFT_APP_ID (same as Client ID above)") or client_id
    bot_password = prompt("MICROSOFT_APP_PASSWORD (same client secret)") or client_secret

    # Write .env snippet
    env_content = f"""# Generated by setup_azure_ad.py
AZURE_TENANT_ID={tenant_id}
AZURE_CLIENT_ID={client_id}
AZURE_CLIENT_SECRET={client_secret}
GRAPH_EXCEL_DRIVE_ID={drive_id}
GRAPH_EXCEL_ITEM_ID={item_id}
GRAPH_EXCEL_SHEET_NAME={sheet_name}
TEAMS_TEAM_ID={team_id}
TEAMS_CHANNEL_ID={channel_id}
MICROSOFT_APP_ID={bot_app_id}
MICROSOFT_APP_PASSWORD={bot_password}
"""
    out_file = ".env.azure"
    with open(out_file, "w") as f:
        f.write(env_content)

    print(f"\n[+] Values written to {out_file}")
    print("    Merge these into your .env file and keep it out of version control.")
    print("\nDone! Run the server and test with Bot Framework Emulator.")


if __name__ == "__main__":
    main()
